#
# * SQL Localization script
# * @package Installer
# * @access private
# * @copyright Copyright 2004-2011 Andrew Berezin eCommerce-Service.com
# * @copyright Copyright 2003 osCommerce
# * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
# * @Localization: Andrew Berezin http://ecommerce-service.com
# * @version $Id: translate_configuration.sql 1.1 22.01.2011 10:07:05 AndrewBerezin eCommerce-Service.com $


#
# Translate configuration_group table
#
UPDATE configuration_group SET configuration_group_title = 'Мой магазин', configuration_group_description = 'Основные настройки магазина.' WHERE configuration_group_id = 1;
UPDATE configuration_group SET configuration_group_title = 'Минимальные значения', configuration_group_description = 'Минимальные значения функций и данных.' WHERE configuration_group_id = 2;
UPDATE configuration_group SET configuration_group_title = 'Максимальные значения', configuration_group_description = 'Максимальные значения функций и данных' WHERE configuration_group_id = 3;
UPDATE configuration_group SET configuration_group_title = 'Картинки', configuration_group_description = 'Настройки картинок.' WHERE configuration_group_id = 4;
UPDATE configuration_group SET configuration_group_title = 'Данные покупателя', configuration_group_description = 'Настройка формы регистрации.' WHERE configuration_group_id = 5;
UPDATE configuration_group SET configuration_group_title = 'Установленные модули', configuration_group_description = 'Скрытые опции.' WHERE  configuration_group_id = 6;
UPDATE configuration_group SET configuration_group_title = 'Доставка/Упаковка', configuration_group_description = 'Настройка опци доставки и упаковки.' WHERE configuration_group_id = 7;
UPDATE configuration_group SET configuration_group_title = 'Вывод товара', configuration_group_description = 'Настройка вывода товара.' WHERE configuration_group_id = 8;
UPDATE configuration_group SET configuration_group_title = 'Склад', configuration_group_description = 'Настройка склада.' WHERE configuration_group_id = 9;
UPDATE configuration_group SET configuration_group_title = 'Логи', configuration_group_description = 'Настройка логов.' WHERE configuration_group_id = 10;
UPDATE configuration_group SET configuration_group_title = 'Кэш', configuration_group_description = 'Настройка кэша.' WHERE configuration_group_id = 11;
UPDATE configuration_group SET configuration_group_title = 'Настройка E-Mail', configuration_group_description = 'Настройка E-Mail.' WHERE configuration_group_id = 12;
UPDATE configuration_group SET configuration_group_title = 'Скачивание', configuration_group_description = 'Настройка скачиваемых товаров.' WHERE configuration_group_id = 13;
UPDATE configuration_group SET configuration_group_title = 'GZip Компрессия', configuration_group_description = 'Настройка GZip компрессии.' WHERE configuration_group_id = 14;
UPDATE configuration_group SET configuration_group_title = 'Сессии', configuration_group_description = 'Session options' WHERE configuration_group_id = 15;

#
# Translate configuration table
#
UPDATE configuration SET configuration_title='Название магазина', configuration_description='Название Вашего магазина' WHERE configuration_key='STORE_NAME';
UPDATE configuration SET configuration_title='Владелец магазина', configuration_description='Имя владельца магазина' WHERE configuration_key='STORE_OWNER';
UPDATE configuration SET configuration_title='E-Mail Адрес', configuration_description='E-Mail адрес владельца магазина' WHERE configuration_key='STORE_OWNER_EMAIL_ADDRESS';
UPDATE configuration SET configuration_title='E-Mail От', configuration_description='E-Mail адрес в отправляемых письмах' WHERE configuration_key='EMAIL_FROM';
UPDATE configuration SET configuration_title='Страна', configuration_description='Страна находения магазина.<br><br><b>Замечание: Не забудьте также указать Зону.</b>' WHERE configuration_key='STORE_COUNTRY';
UPDATE configuration SET configuration_title='Зона', configuration_description='Регион нахождения магазина' WHERE configuration_key='STORE_ZONE';
UPDATE configuration SET configuration_title='Порядок сортировки ожидаемых товаров', configuration_description='Укажите порядок сортировки для ожидаемых товаров, по возрастанию - asc или по убыванию - desc.' WHERE configuration_key='EXPECTED_PRODUCTS_SORT';
UPDATE configuration SET configuration_title='Сортировка ожидаемых товаров', configuration_description='По какому значению будут сортироваться ожидаемые товары.' WHERE configuration_key='EXPECTED_PRODUCTS_FIELD';
UPDATE configuration SET configuration_title='Переключение на валюту текущего языка', configuration_description='Автоматическое переключение цен в магазине на валюту текущего языка.' WHERE configuration_key='USE_DEFAULT_LANGUAGE_CURRENCY';
UPDATE configuration SET configuration_title='Отправка копий писем с заказом', configuration_description='Если Вы хотите получать письма с заказами, т.е. такие же письма, что и получает клиент после оформления заказа, укажите e-mail адрес для получения копий писем в следующем формате: Имя 1 &lt;email@address1&gt;, Имя 2 &lt;email@address2&gt;' WHERE configuration_key='SEND_EXTRA_ORDER_EMAILS_TO';
UPDATE configuration SET configuration_title='Использовать короткие URL адреса (находится в разработке)', configuration_description='Использовать короткие URL адреса в магазине' WHERE configuration_key='SEARCH_ENGINE_FRIENDLY_URLS';
UPDATE configuration SET configuration_title='Переходить в корзину после добавления товара', configuration_description='Переходить в корзину после добавления товара в корзину или оставаться на той же странице.' WHERE configuration_key='DISPLAY_CART';
UPDATE configuration SET configuration_title='Разрешить гостям использовать функцию Рассказать другу', configuration_description='Позволить гостям использовать функцию магазина Рассказать другу, если нет, то данной функцией могут пользоваться только зарегистрированные пользователи магазина.' WHERE configuration_key='ALLOW_GUEST_TO_TELL_A_FRIEND';
UPDATE configuration SET configuration_title='Оператор поиска по умолчанию', configuration_description='Укажите, какой оператор будет использоваться по умолчанию при осуществлении посетителем поиска в магазине.' WHERE configuration_key='ADVANCED_SEARCH_DEFAULT_OPERATOR';
UPDATE configuration SET configuration_title='Адрес и телефон магазина', configuration_description='Здесь Вы можете указать адрес и телефон магазина' WHERE configuration_key='STORE_NAME_ADDRESS';
UPDATE configuration SET configuration_title='Показывать счётчик товаров', configuration_description='Показывает количество товара в каждой категории. При большом количестве товара в магазина рекомендуется отключать счётчик - false, чтобы снизить нагрузку на MySQL сервер, тем самых скорость загрузки страницы Вашего магазина увеличится.' WHERE configuration_key='SHOW_COUNTS';
UPDATE configuration SET configuration_title='Количество знаков после запятой у налогов', configuration_description='Количество знаков после целого числа у налогов.' WHERE configuration_key='TAX_DECIMAL_PLACES';
UPDATE configuration SET configuration_title='Показывать цены с налогами', configuration_description='Показывать цены в магазине с налогами (true) или показывать налог только на заключительном этапе оформления заказа (false)' WHERE configuration_key='DISPLAY_PRICE_WITH_TAX';
UPDATE configuration SET configuration_title='Имя', configuration_description='Минимальное количество символов поля Имя' WHERE configuration_key='ENTRY_FIRST_NAME_MIN_LENGTH';
UPDATE configuration SET configuration_title='Фамилия', configuration_description='Минимальное количество символов поля Фамилия' WHERE configuration_key='ENTRY_LAST_NAME_MIN_LENGTH';
UPDATE configuration SET configuration_title='Дата рождения', configuration_description='Минимальное количество символов поля Дата рождения' WHERE configuration_key='ENTRY_DOB_MIN_LENGTH';
UPDATE configuration SET configuration_title='E-Mail Адрес', configuration_description='Минимальное количество символов поля E-Mail адрес' WHERE configuration_key='ENTRY_EMAIL_ADDRESS_MIN_LENGTH';
UPDATE configuration SET configuration_title='Адрес', configuration_description='Минимальное количество символов поля Адрес' WHERE configuration_key='ENTRY_STREET_ADDRESS_MIN_LENGTH';
UPDATE configuration SET configuration_title='Компания', configuration_description='Минимальное количество символов поля Компания' WHERE configuration_key='ENTRY_COMPANY_MIN_LENGTH';
UPDATE configuration SET configuration_title='Почтовый индекс', configuration_description='Минимальное количество символов поля Почтовый индекс' WHERE configuration_key='ENTRY_POSTCODE_MIN_LENGTH';
UPDATE configuration SET configuration_title='Город', configuration_description='Минимальное количество символов поля Город' WHERE configuration_key='ENTRY_CITY_MIN_LENGTH';
UPDATE configuration SET configuration_title='Регион', configuration_description='Минимальное количество символов поля Регион' WHERE configuration_key='ENTRY_STATE_MIN_LENGTH';
UPDATE configuration SET configuration_title='Телефон', configuration_description='Минимальное количество символов поля Телефон' WHERE configuration_key='ENTRY_TELEPHONE_MIN_LENGTH';
UPDATE configuration SET configuration_title='Пароль', configuration_description='Минимальное количество символов поля Пароль' WHERE configuration_key='ENTRY_PASSWORD_MIN_LENGTH';
UPDATE configuration SET configuration_title='Владелец кредитной карточки', configuration_description='Минимальное количество символов поля Владелец кредитной карточки' WHERE configuration_key='CC_OWNER_MIN_LENGTH';
UPDATE configuration SET configuration_title='Номер кредитной карточки', configuration_description='Минимальное количество символов поля Номер кредитной карточки' WHERE configuration_key='CC_NUMBER_MIN_LENGTH';
UPDATE configuration SET configuration_title='Текст отзыва', configuration_description='Минимальное количество символов для отызов' WHERE configuration_key='REVIEW_TEXT_MIN_LENGTH';
UPDATE configuration SET configuration_title='Лидеры продаж', configuration_description='Минимальное количество товара, выводимого в блоке Лидеры продаж' WHERE configuration_key='MIN_DISPLAY_BESTSELLERS';
UPDATE configuration SET configuration_title='Также заказали', configuration_description='Минимальное количество товара, выводимого в боксе Также заказали' WHERE configuration_key='MIN_DISPLAY_ALSO_PURCHASED';
UPDATE configuration SET configuration_title='Записи в адресной книге', configuration_description='Максимальное количество записей, которые может сделать покупатель в своей адресной книге' WHERE configuration_key='MAX_ADDRESS_BOOK_ENTRIES';
UPDATE configuration SET configuration_title='Товаров на одной странице в каталоге', configuration_description='Количество товара, выводимого на одной странице' WHERE configuration_key='MAX_DISPLAY_SEARCH_RESULTS';
UPDATE configuration SET configuration_title='Ссылок на страницы', configuration_description='Количество ссылок на другие страницы' WHERE configuration_key='MAX_DISPLAY_PAGE_LINKS';
UPDATE configuration SET configuration_title='Специальные цены', configuration_description='Максимальное количество товара, выводимого на странице Скидки' WHERE configuration_key='MAX_DISPLAY_SPECIAL_PRODUCTS';
UPDATE configuration SET configuration_title='Новинки', configuration_description='Максимальное количество товара, выводимых в боксе Новинки' WHERE configuration_key='MAX_DISPLAY_NEW_PRODUCTS';
UPDATE configuration SET configuration_title='Ожидаемые товары', configuration_description='Максимальное количество товара, выводимого в блоке Ожидаемые товары' WHERE configuration_key='MAX_DISPLAY_UPCOMING_PRODUCTS';
UPDATE configuration SET configuration_title='Список производителей', configuration_description='Данная опция используется для настройки бокса производителей, если число производителей превышает указанное в данной опции, список производителей будет выводиться в виде drop-down списка, если число производителей меньше указанного в данной опции, произво' WHERE configuration_key='MAX_DISPLAY_MANUFACTURERS_IN_A_LIST';
UPDATE configuration SET configuration_title='Производители в виде развёрнутого меню', configuration_description='Данная опция используется для настройки бокса производителей, если указана цифра \'1\', то список производителей выводится в виде стандартного drop-down списка. Если указана любая другая цифра, то выводится только X производителей в виде развёрнутого меню.' WHERE configuration_key='MAX_MANUFACTURERS_LIST';
UPDATE configuration SET configuration_title='Ограничение длины названия производителя', configuration_description='Данная опция используется для настройки бокса производителей, Вы указываете количество символов, выводимого в боксе производителей, если название производителя будет состоять из большего количества символов, то будут выведены первые X символов названия' WHERE configuration_key='MAX_DISPLAY_MANUFACTURER_NAME_LEN';
UPDATE configuration SET configuration_title='Новые отзывы', configuration_description='Максимальное количество выводимых новых отзывов' WHERE configuration_key='MAX_DISPLAY_NEW_REVIEWS';
UPDATE configuration SET configuration_title='Выбор случайных отзывов', configuration_description='Количество отзывов, которое будет использоваться для вывода случайного, т.е. если указано X - число отзывов, то случайный отзыв будет выбран из этих X отзывов' WHERE configuration_key='MAX_RANDOM_SELECT_REVIEWS';
UPDATE configuration SET configuration_title='Выбор случайного товара в боксе Новинки', configuration_description='Количество товара, среди которого будет выбран случайный товар и выведен в бокс Новинок, т.е. если указано число X, то новый товар, который будет показан в боксе Новинок будет выбран из этих X новых товаров' WHERE configuration_key='MAX_RANDOM_SELECT_NEW';
UPDATE configuration SET configuration_title='Выбор случайного товара в боксе Скидки', configuration_description='Количество товара, среди которого будет выбран случайный товар и выведен в бокс Скидки, т.е. если указано число X, то товар, который будет показан в боксе Скидки будет выбран из этих X товаров' WHERE configuration_key='MAX_RANDOM_SELECT_SPECIALS';
UPDATE configuration SET configuration_title='Количество категорий в строке', configuration_description='Сколько категорий выводить в одной строке' WHERE configuration_key='MAX_DISPLAY_CATEGORIES_PER_ROW';
UPDATE configuration SET configuration_title='Количество Новинок на странице', configuration_description='Максимальное количество новинок, выводимых на одной странице в разделе Новинки' WHERE configuration_key='MAX_DISPLAY_PRODUCTS_NEW';
UPDATE configuration SET configuration_title='Лидеры продаж', configuration_description='Максимальное количество лидеров продаж, выводимых в боксе Лидеры продаж' WHERE configuration_key='MAX_DISPLAY_BESTSELLERS';
UPDATE configuration SET configuration_title='Также заказази', configuration_description='Максимальное количество товаров в боксе Наши покупатели также заказали' WHERE configuration_key='MAX_DISPLAY_ALSO_PURCHASED';
UPDATE configuration SET configuration_title='Бокс История заказов', configuration_description='Максимальное количество товаров, выводимых в боксе История заказов' WHERE configuration_key='MAX_DISPLAY_PRODUCTS_IN_ORDER_HISTORY_BOX';
UPDATE configuration SET configuration_title='История заказов', configuration_description='Максимальное количество заказов, выводимых на странице История заказов' WHERE configuration_key='MAX_DISPLAY_ORDER_HISTORY';
UPDATE configuration SET configuration_title='Количество товара в корзину', configuration_description='Максимальное количество товара, которое можно положить в корзину (0 - без ограничений)' WHERE configuration_key='MAX_QTY_IN_CART';
UPDATE configuration SET configuration_title='Ширина маленькой картинки', configuration_description='Ширина картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать ширину картинки. Ограничение ширины картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='SMALL_IMAGE_WIDTH';
UPDATE configuration SET configuration_title='Высота маленькой картинки', configuration_description='Высота картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать высоту картинки. Ограничение высоты картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='SMALL_IMAGE_HEIGHT';
UPDATE configuration SET configuration_title='Ширина картинки категории', configuration_description='Ширина картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать ширину картинки. Ограничение ширины картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='HEADING_IMAGE_WIDTH';
UPDATE configuration SET configuration_title='Высота картинки категории', configuration_description='Высота картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать высоту картинки. Ограничение высоты картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='HEADING_IMAGE_HEIGHT';
UPDATE configuration SET configuration_title='Ширина картинки подкатегории', configuration_description='Ширина картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать ширину картинки. Ограничение ширины картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='SUBCATEGORY_IMAGE_WIDTH';
UPDATE configuration SET configuration_title='Высота картинки подкатегории', configuration_description='Высота картинки в пикселах. Оставьте поле пустым или поставьте 0, если не хотите ограничивать высоту картинки. Ограничение высоты картинки не значит физического уменьшения размеров картинки.' WHERE configuration_key='SUBCATEGORY_IMAGE_HEIGHT';
UPDATE configuration SET configuration_title='Вычислять размер картинки', configuration_description='Данная опция просто смотрит переменные, указанные выше и сжимает картинку до указанных размеров, это не значит, что физический размер картинки уменьшится, происходит принудительный вывод картинки определённого размера. Рекомендуется ставить значение false' WHERE configuration_key='CONFIG_CALCULATE_IMAGE_SIZE';
UPDATE configuration SET configuration_title='Картинка обязательна', configuration_description='Необходимо для поиска ошибок, в случае, если картинка не выводится.' WHERE configuration_key='IMAGE_REQUIRED';
UPDATE configuration SET configuration_title='Пол', configuration_description='Показывать поле Пол при регистрации покупателя в магазине и в адресной книге' WHERE configuration_key='ACCOUNT_GENDER';
UPDATE configuration SET configuration_title='Дата рождения', configuration_description='Показывать поле Дата рождения при регистрации покупателя в магазине и в адресной книге' WHERE configuration_key='ACCOUNT_DOB';
UPDATE configuration SET configuration_title='Компания', configuration_description='Показывать поле Компания при регистрации покупателя в магазине и в адресной книге' WHERE configuration_key='ACCOUNT_COMPANY';
UPDATE configuration SET configuration_title='Район', configuration_description='Показывать поле Район при регистрации покупателя в магазине и в адресной книге' WHERE configuration_key='ACCOUNT_SUBURB';
UPDATE configuration SET configuration_title='Регион', configuration_description='Показывать поле Регион при регистрации покупателя в магазине и в адресной книге' WHERE configuration_key='ACCOUNT_STATE';
UPDATE configuration SET configuration_title='Установленные модули', configuration_description='Список установленных модулей оплаты, разделённых точкой с запятой. Страница автоматически обновляется. Ничего изменять не нужно, это просто информативная страница об установленных модулях. (Например: cc.php;cod.php;paypal.php)' WHERE configuration_key='MODULE_PAYMENT_INSTALLED';
UPDATE configuration SET configuration_title='Установленные модули', configuration_description='Список установленных модулей заказ итого, разделённых точкой с запятой. Страница автоматически обновляется. Ничего изменять не нужно, это просто информативная страница об установленных модулях. (Например: ot_subtotal.php;ot_tax.php;ot_shipping.php;ot_tota' WHERE configuration_key='MODULE_ORDER_TOTAL_INSTALLED';
UPDATE configuration SET configuration_title='Установленные модули', configuration_description='Список установленных модулей доставки, разделённых точкой с запятой. Страница автоматически обновляется. Ничего изменять не нужно, это просто информативная страница об установленных модулях. (Например: ups.php;flat.php;item.php)' WHERE configuration_key='MODULE_SHIPPING_INSTALLED';
UPDATE configuration SET configuration_title='Разрешить модуль Оплата наличными при получении', configuration_description='Вы хотите разрешить использование модуля при оформлении заказов?' WHERE configuration_key='MODULE_PAYMENT_COD_STATUS';
UPDATE configuration SET configuration_title='Зона', configuration_description='Если выбрана зона, то данный модуль оплаты будет виден только покупателям из выбранной зоны.' WHERE configuration_key='MODULE_PAYMENT_COD_ZONE';
UPDATE configuration SET configuration_title='Порядок сортировки.', configuration_description='Порядок сортировки модуля.' WHERE configuration_key='MODULE_PAYMENT_COD_SORT_ORDER';
UPDATE configuration SET configuration_title='Статус заказа', configuration_description='Заказы, оформленные с использованием данного модуля оплаты будут принимать указанный статус.' WHERE configuration_key='MODULE_PAYMENT_COD_ORDER_STATUS_ID';
UPDATE configuration SET configuration_title='Валюта по умолчанию', configuration_description='Валюта по умолчанию' WHERE configuration_key='DEFAULT_CURRENCY';
UPDATE configuration SET configuration_title='Язык по умолчанию', configuration_description='Язык по умолчанию' WHERE configuration_key='DEFAULT_LANGUAGE';
UPDATE configuration SET configuration_title='Статус заказа по умолчанию', configuration_description='Статус заказа по умолчанию, присваиваемый новым заказам.' WHERE configuration_key='DEFAULT_ORDERS_STATUS_ID';
UPDATE configuration SET configuration_title='Показывать доставку', configuration_description='Вы хотите показывать стоимость доставки?' WHERE configuration_key='MODULE_ORDER_TOTAL_SHIPPING_STATUS';
UPDATE configuration SET configuration_title='Порядок сортировки', configuration_description='Порядок сортировки модуля.' WHERE configuration_key='MODULE_ORDER_TOTAL_SHIPPING_SORT_ORDER';
UPDATE configuration SET configuration_title='Разрешить бесплатную доставку', configuration_description='Вы хотите разрешить использование модуля бесплатной доставки?' WHERE configuration_key='MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING';
UPDATE configuration SET configuration_title='Бесплатная доставка для заказов на сумму свыше', configuration_description='Заказы, свыше суммы, указанной данной поле, будут доставляться бесплатно.' WHERE configuration_key='MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER';
UPDATE configuration SET configuration_title='Бесплатная доставка для заказов, оформленных из', configuration_description='national - заказы из страны нахождения магазина(переменная Страна магазина), international - заказы из любой страны, кроме страны нахождения магазина, если both - тогда все заказы. При условии, что сумма заказы выше суммы, указанной в переменной выше.' WHERE configuration_key='MODULE_ORDER_TOTAL_SHIPPING_DESTINATION';
UPDATE configuration SET configuration_title='Показывать стоимость товара', configuration_description='Вы хотите показывать стоимость товара?' WHERE configuration_key='MODULE_ORDER_TOTAL_SUBTOTAL_STATUS';
UPDATE configuration SET configuration_title='Порядок сортировки', configuration_description='Порядок сортировки модуля.' WHERE configuration_key='MODULE_ORDER_TOTAL_SUBTOTAL_SORT_ORDER';
UPDATE configuration SET configuration_title='Показывать налог', configuration_description='Вы хотите показывать налог?' WHERE configuration_key='MODULE_ORDER_TOTAL_TAX_STATUS';
UPDATE configuration SET configuration_title='Порядок сортировки', configuration_description='Порядок сортировки модуля.' WHERE configuration_key='MODULE_ORDER_TOTAL_TAX_SORT_ORDER';
UPDATE configuration SET configuration_title='Показывать всего', configuration_description='Вы хотите показывать общую стоимость заказа?' WHERE configuration_key='MODULE_ORDER_TOTAL_TOTAL_STATUS';
UPDATE configuration SET configuration_title='Порядок сортировки', configuration_description='Порядок сортировки модуля.' WHERE configuration_key='MODULE_ORDER_TOTAL_TOTAL_SORT_ORDER';
UPDATE configuration SET configuration_title='Страна магазина', configuration_description='Страна, где находится магазин. Необходимо для некоторых модулей доставки.' WHERE configuration_key='SHIPPING_ORIGIN_COUNTRY';
UPDATE configuration SET configuration_title='Почтовый индекс магазина', configuration_description='Укажите почтовый индекс магазина. Необходимо для некоторых модулей доставки.' WHERE configuration_key='SHIPPING_ORIGIN_ZIP';
UPDATE configuration SET configuration_title='Максимальный вес доставки', configuration_description='Вы можете указать максимальный вес доставки, свыше которого заказы не доставляются. Необходимо для некоторых модулей доставки.' WHERE configuration_key='SHIPPING_MAX_WEIGHT';
UPDATE configuration SET configuration_title='Вес упаковки', configuration_description='Вы можете указать вес упаковки.' WHERE configuration_key='SHIPPING_BOX_WEIGHT';
UPDATE configuration SET configuration_title='Тяжёлые заказы - Процентное увеличение стоимости', configuration_description='Доставка заказов, вес которых больше указанного в переменной Максимальный вес доставки, увеличивается на указанный процент. Если Вы хотите увелить стоимость на 10%, пишите - 10' WHERE configuration_key='SHIPPING_BOX_PADDING';
UPDATE configuration SET configuration_title='Показывать картинку товара', configuration_description='Укажите порядок вывода, т.е. введите цифру. Если укажите 1, то картинка будет слева на первом месте, если 2, то картинка будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_IMAGE';
UPDATE configuration SET configuration_title='Показывать производителя товара', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_MANUFACTURER';
UPDATE configuration SET configuration_title='Показывать код товара', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_MODEL';
UPDATE configuration SET configuration_title='Показывать название товара', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_NAME';
UPDATE configuration SET configuration_title='Показывать стоимость товара', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_PRICE';
UPDATE configuration SET configuration_title='Показывать количество товара на складе', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_QUANTITY';
UPDATE configuration SET configuration_title='Показывать вес товара', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_WEIGHT';
UPDATE configuration SET configuration_title='Показывать кнопку Купить сейчас!', configuration_description='Укажите порядок вывода данного поля в Вашем магазине, т.е. введите цифру. Если укажите 1, то данное поле будет слева на первом месте, если 2, то поле будет показана после(правее) поля, у которого указана цифра 1 и т.д.' WHERE configuration_key='PRODUCT_LIST_BUY_NOW';
UPDATE configuration SET configuration_title='Показывать фильтр Категория/Производители (0=не показывать; 1=показывать)', configuration_description='Показывать бокс(drop-down) меню, с помощью которого можно сортировать товар в какой-либо категории магазина по Производителю.' WHERE configuration_key='PRODUCT_LIST_FILTER';
UPDATE configuration SET configuration_title='Расположение навигации Следующая/Предыдущая страница', configuration_description='Установите расположение навигации Следующая/Предыдущая страница (1-верх, 2-низ, 3-верх+низ)' WHERE configuration_key='PREV_NEXT_BAR_LOCATION';
UPDATE configuration SET configuration_title='Проверять наличие товара на складе', configuration_description='Проверять, есть ли необходимое количество товара на складе при оформлении заказа' WHERE configuration_key='STOCK_CHECK';
UPDATE configuration SET configuration_title='Вычитать товар со склада', configuration_description='Вычитать со склада то количество товара, которое будет заказываться в интернет-магазине' WHERE configuration_key='STOCK_LIMITED';
UPDATE configuration SET configuration_title='Разрешить оформление заказа', configuration_description='Разрешить покупателям оформлять заказ, даже если на складе нет достаточного количества единиц заказываемого товара' WHERE configuration_key='STOCK_ALLOW_CHECKOUT';
UPDATE configuration SET configuration_title='Отмечать товар, отсутствующий на складе', configuration_description='Показывать покупателю маркер напротив товара при оформлении заказа, если на складе нет необходимого количества единиц заказываемого товара' WHERE configuration_key='STOCK_MARK_PRODUCT_OUT_OF_STOCK';
UPDATE configuration SET configuration_title='Лимит количества товара на складе', configuration_description='Если количество товара на складе меньше, чем указанное число в данной переменной, то в корзине выводится предупреждение о недостаточном количестве товара на складе для выполнения заказа.' WHERE configuration_key='STOCK_REORDER_LEVEL';
UPDATE configuration SET configuration_title='Сохранять время парсинга страниц', configuration_description='Хранить время, затраченное на генерацию(парсинг) страниц магазина.' WHERE configuration_key='STORE_PAGE_PARSE_TIME';
UPDATE configuration SET configuration_title='Директория хранения логов', configuration_description='Полный путь до директории и файла, в который будет записываться лог парсинга страниц.' WHERE configuration_key='STORE_PAGE_PARSE_TIME_LOG';
UPDATE configuration SET configuration_title='Формат даты логов', configuration_description='Формат даты' WHERE configuration_key='STORE_PARSE_DATE_TIME_FORMAT';
UPDATE configuration SET configuration_title='Показывать время парсинга страниц', configuration_description='Показывать время парсинга страницы в интернет-магазине (опция Сохранять время парсинга страниц должна быть включена)' WHERE configuration_key='DISPLAY_PAGE_PARSE_TIME';
UPDATE configuration SET configuration_title='Сохранять запросы к базе дынных', configuration_description='Сохранять все запросы к базе данных в файле, указанном в переменной Директория хранение логов (только для PHP4 и выше)' WHERE configuration_key='STORE_DB_TRANSACTIONS';
UPDATE configuration SET configuration_title='Использовать кэш', configuration_description='Использовать кэширование информации.' WHERE configuration_key='USE_CACHE';
UPDATE configuration SET configuration_title='Кэш директория', configuration_description='Директория, куда будут записываться и сохраняться кэш-файлы.' WHERE configuration_key='DIR_FS_CACHE';
UPDATE configuration SET configuration_title='Способ отправки E-Mail', configuration_description='Укажите, какой способ отправки писем из магазина будет использоваться. Для серверов, работающих под управлением Windows или MacOS необходимо установить SMTP для отправки писем.' WHERE configuration_key='EMAIL_TRANSPORT';
UPDATE configuration SET configuration_title='Разделитель строк в E-Mail', configuration_description='Используемая последовательность символов для разделения заголовков в письме.' WHERE configuration_key='EMAIL_LINEFEED';
UPDATE configuration SET configuration_title='Использовать HTML формат при отправке писем', configuration_description='Отправлять письма из магазина в HTML формате.' WHERE configuration_key='EMAIL_USE_HTML';
UPDATE configuration SET configuration_title='Проверять E-Mail адрес через DNS', configuration_description='Проверять, верные ли e-mail адреса указываются при регистрации в интернет-магазине. Для проверки используется DNS.' WHERE configuration_key='ENTRY_EMAIL_ADDRESS_CHECK';
UPDATE configuration SET configuration_title='Отправлять письма из магазина', configuration_description='Отправлять письма из мгаазина.' WHERE configuration_key='SEND_EMAILS';
UPDATE configuration SET configuration_title='Разрешить функцию скачивания товаров', configuration_description='Разрешить функцию скачивания товаров.' WHERE configuration_key='DOWNLOAD_ENABLED';
UPDATE configuration SET configuration_title='Использовать перенаправление при скачивании', configuration_description='Использовать перенаправление в браузере для скачивания товара. Для не Unix систем(Windows, Mac OS и т.д.) должно стоять false.' WHERE configuration_key='DOWNLOAD_BY_REDIRECT';
UPDATE configuration SET configuration_title='Срок существования ссылки для скачивания (дней)', configuration_description='Установите количество дней, в течение которых покупатель может скачать свой товар. Если укажите 0, тогда срок существования ссылки для скачивания ограничен не будет.' WHERE configuration_key='DOWNLOAD_MAX_DAYS';
UPDATE configuration SET configuration_title='Максимальное количество скачиваний', configuration_description='Установите максимальное количество скачиваний для одного товара. Если укажите 0, тогда никаких ограничений по количеству скачиваний не будет.' WHERE configuration_key='DOWNLOAD_MAX_COUNT';
UPDATE configuration SET configuration_title='Разрешить GZip компрессию', configuration_description='Разрешить HTTP GZip компрессию.' WHERE configuration_key='GZIP_COMPRESSION';
UPDATE configuration SET configuration_title='Уровень компрессии', configuration_description='Вы можете указать уровень компрессии от 0 до 9 (0 = минимум, 9 = максимум).' WHERE configuration_key='GZIP_LEVEL';
UPDATE configuration SET configuration_title='Директория сессий', configuration_description='Если сессии хранятся в файлах, то здесь необходимо указать полный путь до папки, в которой будут храниться файлы сессий.' WHERE configuration_key='SESSION_WRITE_DIRECTORY';
UPDATE configuration SET configuration_title='Принудительное использование Cookie', configuration_description='Принудительно использовать сессии, только когда в браузере активированы cookies.' WHERE configuration_key='SESSION_FORCE_COOKIE_USE';
UPDATE configuration SET configuration_title='Проверять ID SSL сессии', configuration_description='Проверять  SSL_SESSION_ID при каждом обращении к странице, защищённой протоколом HTTPS.' WHERE configuration_key='SESSION_CHECK_SSL_SESSION_ID';
UPDATE configuration SET configuration_title='Проверять переменную User Agent', configuration_description='Проверять переменную бразура user agent при каждом обращении к страницам интернет-магазина.' WHERE configuration_key='SESSION_CHECK_USER_AGENT';
UPDATE configuration SET configuration_title='Проверять IP адрес', configuration_description='Проверять IP адреса клиентов при каждом обращении к страницам интернет-магазина.' WHERE configuration_key='SESSION_CHECK_IP_ADDRESS';
UPDATE configuration SET configuration_title='Не показывать сессию в адресе паукам поисковых машин', configuration_description='Не показывать сессию в адресе при обращении к станицам магазина известных поисковых пауков. Список известных пауков находится в файле includes/spiders.txt.' WHERE configuration_key='SESSION_BLOCK_SPIDERS';
UPDATE configuration SET configuration_title='Воссоздавать сессию', configuration_description='Воссоздавать сессию для генерации нового ID кода сессии при входе зарегистрированного покупателя в магазин, либо при регистрации нового покупателя (Только для PHP 4.1 и выше).' WHERE configuration_key='SESSION_RECREATE';
UPDATE configuration SET configuration_title='Last UPDATE Check Time', configuration_description='Last time a check for new versions of osCommerce was run' WHERE configuration_key='LAST_UPDATE_CHECK_TIME';
UPDATE configuration SET configuration_title='Установленные группы блока шаблона', configuration_description='This is automatically updated. No need to edit.' WHERE configuration_key='TEMPLATE_BLOCK_GROUPS';
UPDATE `configuration` SET `configuration_title`='Сортировка' WHERE `configuration_title`='Sort Order';
UPDATE `configuration` SET `configuration_description`='Порядок сортировки' WHERE `configuration_description`='Sort order of display. Lowest is displayed first.';
UPDATE `configuration` SET `configuration_description`='Добавить модуль?' WHERE `configuration_description`='Do you want to add the module to your shop?';
UPDATE `configuration` SET `configuration_description`='Модуль показывать в левой или правой колонке?' WHERE `configuration_description`='Should the module be loaded in the left or right column?';
UPDATE `configuration` SET `configuration_title`='Ширина' WHERE `configuration_title`='Content Width';
UPDATE `configuration` SET `configuration_description`='Укажите ширину. 12 - полная ширина, 6 - половина.' WHERE `configuration_description`='What width container should the content be shown in? (12 = full width, 6 = half width).';
UPDATE `configuration` SET `configuration_title`='Разрешить заказы не соответствующие определённым зонам доставки' WHERE `configuration_key`='SHIPPING_ALLOW_UNDEFINED_ZONES';
UPDATE `configuration` SET `configuration_description`='Разрешить заказы не соответствующие определённым зонам доставки?' WHERE `configuration_key`='SHIPPING_ALLOW_UNDEFINED_ZONES';
UPDATE `configuration` SET `configuration_title`='Адрес магазина' WHERE `configuration_key`='STORE_ADDRESS';
UPDATE `configuration` SET `configuration_description`='Адрес магазина используется на печатных документах и отображается на сайте' WHERE `configuration_key`='STORE_ADDRESS';
UPDATE `configuration` SET `configuration_title`='Телефон магазина' WHERE `configuration_key`='STORE_PHONE';
UPDATE `configuration` SET `configuration_description`='Телефон магазина используется на печатных документах и отображается на сайте' WHERE `configuration_key`='STORE_PHONE';